int _putchar(char c);
int _putchar(char c);
int _islower(int c);
int _isalpha(int c);
int _abs(int n);
int _isupper(int c);
int _isdigit(int c);
int _strlen(char *s);
int _atoi(char *s);
int _strcmp(char *s1, char *s2);
